### ISSUE TITLE
image/png handling

### ISSUE THREAD

**Issue by BarbUk** [erebe/greenclip#16]
Hello, thanks a lot for this great tool.

Is this possible to handle image mime type ?
If I do a screenshot and put it in the clipboard, it appear in the history.

For example:
`maim --select --hidecursor --highlight --color=0.3,0.4,0.6,0.3 --bordersize=3 --format=png --quality=10 | xclip -selection clipboard -t image/png`

But if I select it in rofi, I have just the following in the clipboard
�PNG



**Comment by erebe** [comment]
Hello,

Sadly I will not implement the feature as due to how rofi and greenclip interact with each other, the end result will be flaky.

**Comment by erebe** [comment]
Hello,

Sadly, I will not implement the feature as due to how rofi and greenclip interact with each other, the end result will suck without a lot of rework.
Rofi doesn't know about greenclip and greenclip does not know about Rofi. 
Rofi responsibility is to display a list of lines and greenclip responsibility is to provide this list and advertise the selected one. 
In order to support image handling, I should convert them to their hash each time you want to display the history which will be quite expansive and slow for big images or if you have a lot of images in your history. 
So I will have to change the backend format from a flat file to something smarter to avoid doing this.

Once the new backend is ready, I will have to implement mime support in greenclip, which seems to be full of legacy tricks from what I can see from other clipboard-managers.

While this is technically feasible, I doubt I will implement it as it require a lot of rework (and debugging sessions) for it to be viable. Maybe in a 3.0 version but for now I don't have a lot of free time.

**Comment by erebe** [comment]
I released a 3.0-beta with mime support (images at least) https://github.com/erebe/greenclip/releases/tag/3.0
You can give it a shot if you want.

Be aware that it only handle small images < 500ko as beyond it use an incremental protocol to transfer data and as due to how greenclip interact with other clipboard app (it does not steal it in order to not break other apps features) it consume to much CPU.

**Comment by BarbUk** [comment]
just tested it, it works really well.

I had to remove ~/.cache/greenclip.history before starting the daemon because of an error:
```
~ ❯ greenclip print
greenclip: Data.Binary.Get.runGet at position 104: not enough bytes
CallStack (from HasCallStack):
  error, called at libraries/binary/src/Data/Binary/Get.hs:342:5 in binary-0.8.3.0:Data.Binary.Get
```

**Comment by erebe** [comment]
Thanks for reporting it, I should put a warning somewhere for the migration.
