### ISSUE TITLE
Ignore content from some application

### ISSUE THREAD

**Issue by fikovnik** [erebe/greenclip#17]
Greenclip is excellent! Would it be possible not to store content coming from certain apps in the static history? I don't know how the clipboard protocol works on X11, but on OSX it was possible to figure out the origin application and ignore certain apps such as password managers.

**Comment by erebe** [comment]
Hello,

Right now, no because I don't have enough spare time to work on it. 
But I already planned to add mime support for a 3.0 version. So adding a blacklist feature so not be to much additional work if planned in advance.

In the mean time you can follow the explanation here https://github.com/erebe/greenclip/issues/5 if you don't want that some password end-up in your history

**Comment by erebe** [comment]
I released a 3.0-beta with blacklist support https://github.com/erebe/greenclip/releases/tag/3.0
You can give it a shot if you want.
To know the name of the application, just start greenclip daemon in the foreground and it will tell you the name of the app when you copy something from it.

Be aware that a lot of application does not give name to the process owning the selection. So it will appear as "". 
An other issue also, is with the raising popularity of apps based on electron/chromium headless you will see a lot of app taking the name of "Chromium clipboard"
