### ISSUE TITLE
Can I specify the size limits of selection and clipboard separately?

### ISSUE THREAD

**Issue by qwIvan** [erebe/greenclip#22]
Because my selection has too much content.

**Comment by erebe** [comment]
Why do you want to do that, is there a problem if the selection is too large ?
In which scenario do you think a truncate selection can be useful in any ways ?

**Comment by qwIvan** [comment]
@erebe I means that there are a lot of operation will using selection.
When I editing some text, I use `Ctrl+A` and `delete` to delete all content, I use shift + up/down arrow to select line of text than deleted it.
When I browse I select some text then right click to "search keyword in Google", I select some English word translate to Chinese because I doesn't well at English.

**Comment by qwIvan** [comment]
I also hope to add some feature to limit length of each entry, otherwise the matching would be too slow after I copy a large text.

**Comment by erebe** [comment]
Have you this option `usePrimarySelectionAsInput` set to `True` in your config file ?
If yes I recommend you to set it to `False`. 

By doing so content will be selected only if you do a `Ctrl+C` so you will not be enoyed when doing 'Ctrl+A` and `Delete` or when just selecting som text.

**Comment by qwIvan** [comment]
@erebe but I also want to use primary selection...

**Comment by erebe** [comment]
Well there is actually no way to limit by the size of the selection, and I will not implement it, as for me it is silly workaround for using the primarySelection.

**Comment by erebe** [comment]
Well there is actually no way to limit by the size of the selection, and I will not implement it, as for me it is silly workaround for using the primarySelection.

If you want to use `usePrimarySelectionAsInput` because you want to copy/paste text from your terminal, there is a lot of plugin to that for you.
for urxvt https://www.mankier.com/1/urxvt-selection-to-clipboard
I know it is possible to do it also for st terminal
