### ISSUE TITLE
Greenclip v3.0 crashing

### ISSUE THREAD

**Issue by exic** [erebe/greenclip#32]
Greenclip is crashing for me sometimes now:

X Error of failed request:  BadAtom (invalid Atom parameter)
  Major opcode of failed request:  17 (X_GetAtomName)
  Atom id in failed request:  0x72656863
  Serial number of failed request:  30988
  Current serial number in output stream:  30988

Wasn't able to reproduce the cause, yet.

I also uninstalled my self-compiled greenclip and downloaded the "official" one again.

Ubuntu 18.04
i3 4.15.0.1-161-g19735b5e (2018-05-04, branch "gaps-next")

If you need any more data, please tell me.

**Comment by erebe** [comment]
I've played a bit ubuntu 18.04 and i3 (the one you get by doing `apt install-i3-vm`) but I haven't got any crashes. So I can't help you with that, as I can't reproduce the issue...

But from the error you have, it should either be a bug in I3 or in a specific app.
Atom are ids for window property that are exchanged instead of the actual name (string) of the property in order for the protocol to be memory efficient. 
The part that is failling is when I ask to the app owning the clipboard: "Hey please give me the list of atom for your clipboard " in order to know which mime type (text, image) the selection is in.
After getting this list, I am asking to get the actual mime name (XGetAtomName) of each atom returned but one of them seems to be utterly garbage ( 0x72656863 looks like a memory address to me)

**Comment by exic** [comment]
I ran `greenclip daemon || notify-send -u critical 'murks!'` and found out that neovim is the causing it. I'm running v0.2.2 with `set clipboard=unnamed` (ran `nvim -u NONE`, so no other settings were changed). Yanking something (like `yy`) causes greenclip to crash. Can you reproduce?

**Comment by erebe** [comment]
nop sorry :"'( I can't reproduce.

What I have done in a Virtualbox

1. Install an ubuntu 18.04 desktop version (in a minimal setup)
2. Install i3 with `apt install i3`
3. Install greenclip 3.0 with `wget https://github.com/erebe/greenclip/releases/download/3.0/greenclip; chmod +x; sudo mv greenclip /usr/local/bin`
4. Install neovim with `apt install neovim`
4. Restart the VM and log into i3 
5. Start a terminal where I run `greenclip daemon` in foreground
6. Start an other terminal where i run `nvim -u NONE`
7. Do a `:set clipboard=unnamed` in neovim
8. Do some yanking `yy`

But no crash, the daemon do not even see that a selection (nor the clipboard of the system) has been made available.

The only way for the daemon to notice that there is a new selection available is by doing
`:set clipboard=unnamedplus` instead of just unnamed, but even there I don't have any crashes just that greenclip and the system get notified that neovim is exporting a new selection when doing `yy`

what behavior do you have if you use `:set clipboard=unnamedplus` instead of unnamed ?

**Comment by exic** [comment]
Ah sorry I forgot to mention that I also have `usePrimarySelectionAsInput = True` configured:

```
$ cat ~/.config/greenclip.cfg 
Config {
 maxHistoryLength = 50,
 historyPath = "~/.cache/greenclip.history",
 staticHistoryPath = "~/.cache/greenclip.staticHistory",
 imageCachePath = "/tmp/",
 usePrimarySelectionAsInput = True,
 blacklistedApps = []
}
```

**Comment by erebe** [comment]
Still no issue with lastest termite and `usePrimarySelectionAsInput = True`.
Can you try installing the latest version of termite (I used this script https://raw.githubusercontent.com/Corwind/termite-install/master/termite-install.sh) because it seems that a lot of recent commits on the project has been fixing stuff regarding clipboard
https://github.com/thestinger/termite/commit/01bfd9f9ea8d0d05b063bc43a5121860ccc8d8a2
https://github.com/thestinger/termite/commit/3bc2a43bef9b0842cb242dd19853d0344c8a2766
and some more

**Comment by exic** [comment]
Thanks for checking and finding out about the fixes. I upgraded my termite installation and will report back. So far it looks good :-)

**Comment by exic** [comment]
I guess that fixed it. No more issues :+1:

**Comment by exic** [comment]
I'm afraid I'm still getting it sometimes. Since I'm now running greenclip in an infinite loop now, I can still use it. However, should the misbehavior of a third party program be able to crash greenclip or shouldn't greenclip just say 'ok looks like I can't use that, let's just ignore it' :-)?

Can I maybe enable "debug mode" or increase verbosity to provide some more information?

Current versions:
NVIM v0.3.0
termite v13-11-g3e2c10f
i3 version 4.15.0.1-2-g1c535b18 (2018-03-13, branch "gaps")

**Comment by erebe** [comment]
Arg you again ! Go outside drink some beers, that's summer !

That's not that a third program is able to crash me, it is that it is sending me false information that I try to interpret/reuse and I'm crashing myself (Xorg killing my window in fact).

I am not sure that I can recover from Xorg wanting to kill my window, nor if I can detect when someone is sending me false information.

Will take a look at it, but don't expect anything soon

**Comment by exic** [comment]
Too bad I have to work sometimes and can't drink beer all the time :-D

Greenclip has enriched my life (also work life) quite a bit so far. So I'd really love to have it running reliably and also save others that frustration of "oh no why is my selection gone now – oh greenclip daemon not running any more".

So of course I also always want to use friendly other programs that don't send false information (and if they do, fix those too), but I'm not sure if I can always rely on everything being safe. So I might have a look at the code of both programs ;-)

Thanks for your time and your program, have a nice weekend!

**Comment by erebe** [comment]
re-open if needed

**Comment by exic** [comment]
Looks good so far, thanks a lot!
