### ISSUE TITLE
Strange behavior when clearing the clipboard

### ISSUE THREAD

**Issue by chrissound** [erebe/greenclip#34]
```
[chris@archamd greenclip]$ ~/.local/bin/greenclip print "abc"
[chris@archamd greenclip]$ ~/.local/bin/greenclip clear
[chris@archamd greenclip]$ ~/.local/bin/greenclip print
[chris@archamd greenclip]$ ~/.local/bin/greenclip print "abc"
[chris@archamd greenclip]$ ~/.local/bin/greenclip print
[chris@archamd greenclip]$ ~/.local/bin/greenclip print "abc2"
[chris@archamd greenclip]$ ~/.local/bin/greenclip print
abc2
abc
testeuueoaaueeuo ueoeuo ueoa
testeuueoaaueeuo ueoeuo
testeuueoa
```
1. In the above I would expect it to add `abc` to the clipboard with. But it also seems to occur if the text is different from the last copied text.

2. On the last command I would expect it only to have `abc` and `abc2`, however it is showing all the previous history?

**Comment by erebe** [comment]
Ha yeah, I often got questions about this command, as its behaviour is a bit counter intuitive.

Basically the clear command is just an `rm -f` of your history file but you can't do it while the daemon is running as it keeps the history also in memory and will reflush on disk after a new get discovered.

The only purpose of the command is calling it before you start the daemon in order to clear your hsitory.

**Comment by sQVe** [comment]
@erebe I think the expected behavior is more in line with `pkill greenclip && greenclip clear && greenclip daemon &`.

**Comment by graves501** [comment]
I put my history file in `/tmp` to clear it with every reboot. I actually thought that `greenclip clear` gets rid of the current cache. So thank you @sQVe for pointing out what I actually expected.

**Comment by vxcamiloxv** [comment]
yes, it's is and expected behavior looks more like a bug, also would be useful to remove a single item
