### ISSUE TITLE
Ignore new line symbol

### ISSUE THREAD

**Issue by Crandel** [erebe/greenclip#38]
Hi,
Some time ago I started using rofi and this clipboard tool and today I tried to copy new line symbol to do some replacement in text, but greenclip ignore this symbol and doesn`t show it in history.
I work a lot with text formatting and used clipit to replace some symbol with this symbol + new line symbol. It helps to unuglify source code. I need this functionality in greenclip.

**Comment by erebe** [comment]
Hello,

This is due because I trim text selection https://github.com/erebe/greenclip/blob/master/src/Clipboard.hs#L165. So if your input contains only space/newlines it will collapse into an empty string and will be discarded later on in the program.

I may add an option to toggle or not the trimming of the selection, but for now I don't have much free time.
So don't expect anything before the end of the month

**Comment by Crandel** [comment]
Thank you, I will wait

**Comment by Crandel** [comment]
Thank you very much
