### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by dealelopez** [erebe/greenclip#41]
The version of the new release is the 3.2 but executing `./greenclip -v` it says `v 3.1`.
Is everything ok?

**Comment by erebe** [comment]
yeah I know ... that's because I pushed the tag 3.2 https://github.com/erebe/greenclip/tree/3.2 before changing the version in the code.
Once I realised my mistake, I already had pushed the binary in various repository, so I was too lazy to re-do the build and re-fix everything...
I was hoping nobody noticed

**Comment by dealelopez** [comment]
Sorry then... xD
