### ISSUE TITLE
Latest clipboard element listed with ps|htop

### ISSUE THREAD

**Issue by edoz90** [erebe/greenclip#46]
Hi!

When an element is copied to the clipboard buffer it's possible to see it using `ps`, `htop` (or any other similar program) as if the process is still running.

![screenshot 2018-11-30 19 47 27](https://user-images.githubusercontent.com/6991986/49308520-d21c8d80-f4d8-11e8-87ad-d0eba1c3847d.png)

![greenclip](https://user-images.githubusercontent.com/6991986/49308429-9681c380-f4d8-11e8-8eeb-019f45c968de.png)

After a couples of minutes (> 4) the process is killed.

**Comment by erebe** [comment]
Hello,
This is normal. In the X11 protocol the clipboard is hold by a process in order to avoid copying data between the origin process and the X11 server. This is in case that the selection is never asked by anybody.

So when you request a selection from greenclip, the program is forking an other process in order to tell the X11 server that it is now the owner of the clipboard and to respond to other process wanting to get the selection (in X11 windows send messages between them in order to get information).
The greenclip forked process dies only when a new process/windows is claiming to be the owner of the clipboard.

**Comment by edoz90** [comment]
Hi!

Thank you for the explanation, I didn't know about this!

So there is no way to prevent this behaviour? I know that the clipboard is shared across al processes so this is not a security concern, just an OCD thing :)

Feel free to close.

**Comment by erebe** [comment]
Well technically you can prevent it by letting the greenclip daemon also manage the selected selection.
But I would need to code the communication between the processes, which I would rather avoid as it add some complexity.

**Comment by tomterl** [comment]
Would it be easier to let the 'print' command read from a pipe or stdin instead of giving the clipping as a parameter? That way the crucial part would be hidden in the ps output, without changing anything else.  My haskell is quasi non existent, appart from a few exercism.io lessons, but if you think this might be acceptable, I'd give it shot in my upcoming vacation time.
