### ISSUE TITLE
is there a way to inject ssh entries into greenclip?

### ISSUE THREAD

**Issue by basaran** [erebe/greenclip#51]
Hello,
Thank you for greenclip. Can we add ~/.ssh/config into greenclip so one can search/yank the ssh host and paste into tmux ?

**Comment by erebe** [comment]
Hello,

You can't do it directly with greenclip (and I don't plan to add such feature)
But you can use the staticHistory feature to put what ever you want always present in the greenclip available selection.
So when you start your session, just parse your ssh config file in order to dump the entries that you want into the file of the staticHistory.

Let me know if it not clear enough :)

**Comment by basaran** [comment]
Very clear, thank you very much. Static history add was what I was looking for. Good day.
