### ISSUE TITLE
Trim spaces parameter in config file

### ISSUE THREAD

**Issue by dealelopez** [erebe/greenclip#52]
I have the config shared among multiple computers and from one to another the `trimSpaceFromSelection` config parameter is being modified.
Is this normal? I'm not able to share the config between two computers?
```
@@ -4,5 +4,6 @@ Config {
  staticHistoryPath = "~/.cache/greenclip.staticHistory",
  imageCachePath = "/tmp/",
  usePrimarySelectionAsInput = False,
- blacklistedApps = []
+ blacklistedApps = [],
+ trimSpaceFromSelection = True
 }
```

**Comment by erebe** [comment]
Download the latest version on greenclip on both of your computer.
I have added the trim option in the 3.2 https://github.com/erebe/greenclip/releases/tag/3.2 and in order to not break the config when migrating, I had the default option automatically if not present.

So one of your computer shall have an older version installed :)

**Comment by dealelopez** [comment]
Alright! Thanks.
I haven't thought of that. I don't know which one has which version because version 3.2 shows is version 3.1. I'll upgrade all computers.

**Comment by dealelopez** [comment]
No worries, this awesome clipboard compensates that little things. :)
