### ISSUE TITLE
Prev/Next commands?

### ISSUE THREAD

**Issue by solars** [erebe/greenclip#53]
Hi there,

Not sure if there is an option but it would be nice to control the current selection with prev/next commands.

I want to bind my mouse up/down keys to the clipboard to quickly select contents. Ideally it would output the content so it could be used with a notification daemon like dunst.

**Comment by erebe** [comment]
Hello,

I can't do that at greenclip level, you have to dig into rofi configuration in order to know if it is possible to override keybinds

**Comment by solars** [comment]
Hi, thanks for the answer!
Yes I know, but it would be nice if greenclip would support commands to select a particular entry or to have something like "next" "previous" entry in list.
Then you could bind this to prev/next buttons. And with a keypress automatically select the next entry in the paste buffer.

I could do it with print and then select a particular row in the greenclip output, but it gets complicated since greenclip reorders the list. Thus, if you would use next (index=1) you would always get the same two entries.

**Comment by erebe** [comment]
The plugin system in rofi is fairly simple. The only interaction that I can get is
- Being called without argument
- Being called with a selection as argument

So what you want to achieve is not really possible.
The only possible option that I can see that would work would be introducing in greenclip special strings that a user would have to type in order to mimic comands.
But I will not add this kind of feature as 
- I don't like the design of it
- It would require that I implement a communication mechanism with the daemon, which will require a lot of work

**Comment by solars** [comment]
Alright, thank you
