### ISSUE TITLE
greenclip: Cannot decode byte '\x65' with french chars

### ISSUE THREAD

**Issue by sheoak** [erebe/greenclip#54]
if running:

`rofi -modi 'clipboard:greenclip print' -show clipboard -run-command '{cmd}'`

The command failed due to a french char (é) in the static history file:

`greenclip: Cannot decode byte '\x65': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream`

```
$ file ~/.greenclip.staticHistory
~/.greenclip.staticHistory: UTF-8 Unicode text
```

**Comment by erebe** [comment]
That's because for what ever reason that not real UTF-8.
Do 
```
iconv -f latin1 -t utf-8 ~/.greenclip.staticHistory > tmp.history
mv tmp.history  ~/.greenclip.staticHistory 
```

Should work better after that, let me know if it is not the case

**Comment by sheoak** [comment]
Yes it worked. Strange, I never had any issues with vim and utf-8. Thanks!

**Comment by siddbudd** [comment]
I tried that iconv line and moved the converted file back but got the same error. I tried editing in vim and gvim. Otherwise I only have bloated text editors that support utf8, such as wps or libreoffice. 
➜  .cache rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}'
`greenclip: Cannot decode byte '\xfc': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream`
➜  .cache cat greenclip.staticHistory
> Beste Grüße, Gabor

**Comment by erebe** [comment]
Hello,
For me the iconv trick works, I got at first the same error 
`greenclip: Cannot decode byte '\xfc' ...` but after replacing the file by the one generated by iconv, it is ok.

What locale do you have when you do in a shell  
> locale
?
