### ISSUE TITLE
Command line option to delete an entry

### ISSUE THREAD

**Issue by xsteve** [erebe/greenclip#63]
Hi,
it would be nice to have a way to delete one or several entries somehow.

e.g. "greenclip remove 2 6"

This would remove the entries 2 and 6 from the history (I don't care if it is 0 or 1 based)

"greenclip print | nl" could be used to show the index values (1 based)

That way I could remove for example a password from the clipboard history...

**Comment by erebe** [comment]
Hello,
I think this feature have been already been requested before.
I won't do it because I don't have time/want to bring this project much further and that adding this feature is not trivial.

Greenclip daemon keep in memory your history and re-flush to disk when there is a change. In order to be able to delete entries from greenclip, I would need a way to communicate with the daemon for it to delete the entries from its memory history. 
While this is completely do-able with IPC, this is something that does not exist at all inside the project so I will need spend a bit of time if I want to add it.

So sadly, I am happy with the state of the project right now and I don't want to spend that amount of time to add IPC inside greenclip ;'(

**Comment by xsteve** [comment]
Thanks for your explanation.
I like the architecture of greenclip. Sadly I don't know how to program in Haskell. So I can't do this myself.

In python I have used zeromq or nanomsg to do IPC

There is even a nanomsg-haskell binding:
http://hackage.haskell.org/package/nanomsg-haskell

Thanks for creating greenclip. And I fully understand that you don't find the time to implement new features...
