### ISSUE TITLE
Heavy lags when copying large images

### ISSUE THREAD

**Issue by Alexey104** [erebe/greenclip#71]
Hi!
Thanks for greenclip, it's awesome! 
But i have the following problem with it: when i copy any large image from any app, this app instantly becomes so laggy and unresponsive that i cannot use it anymore until i kill greenclip or select some plain text from the buffer. For instance, if i copy high resolution wallpaper from Firefox to clipboard via Ctrl+C, i cannot browse anymore due to heavy GUI/scrolling lags in Firefox. If i then copy some plain text or select already saved from the buffer, these lags instantly disappear. 

Is there any way i can fix this issue?
Thanks!

**Comment by afreakk** [comment]
It seems to not ignore big images, id like for greenclip to just ignore images, atleast have an option for it.

**Comment by erebe** [comment]
Hello,

Sadly nope, it is inherent to the way greenclip handle selection and cannot be worked around.
In the X protocol, the clipboard selection is managed by the application owning it. When you do a ctrl+c, the window tells X server that it wants to be the owner of the clipboard now, so the next request of "get selection" or ctrl+v should be directed to this window by the X server.
So there is never copy of the data between the window and the X server, the server only change which window is currently owning the clipboard selection and that's the window that transmit the selection's content when requested by an other window.

"Traditionnal" clipboard manager for X behave this way. 

1. Request to X the ownership of the clipboard
2. Wait for a window to request the ownership and thus get notified when it lose the clipboard
3. Immediately after losing the ownership, it ask to X the content of the clipboard and record it its process
4. After getting the new content, ask to X to be again the owner of the clipboard 
5. Start advertising the content that it stole from the previous owner

This way of doing thing is great for performance, but means that the clipboard manager is effectively always the owner of the selection.
Having the clipboard manager be the owner of all selection sucks as it will break subtly all applications that do not just do "text". When requesting clipboard, the X protocol allow specifying the mime format you want for your selection (i.e: image, audio, html, ...) as the clipboard manager stole the selection there is no way it can handle multiple mime, or do some conversion, it just to default to one, and sadly in practice it breaks ctrl+c/ctrl+v of many applications (i.e: firefox)

So to avoid breaking the clipboard of app, greenclip behave differently. Instead of stealing the ownership of the selection, it just poll the content and record it if it changed, and it is only when you want to change the content of the selection (with rofi) that it steals the selection and advertise the one you want. This is great because now your apps are not broken anymore as they are still the owner of the clipboard when you don't want to change it, but it not so great for performance as you request the content very often and thus copy many time the data.

In practice when the selection is small, you don't see it at all, but when in you case the content of the selection is big it will start to burn your cpu by fetching non-stop a big chunk of data.
if the selection is too big greenclip does not copy it, but the initial buffer size is dependent of the X server and can be nowaday quite big by default (several megabytes), so it makes the X server lag and churn your cpu...

So to sump-up, that's a downside of the core design decision of greenclip not willing to break clipboard of applications and it cannot be worked around. 
The clipboard management of the X protocol is just plain nightmare as it is a pile of extension upon others and just force you to choose your poison.

**Comment by Alexey104** [comment]
@erebe, Hi!

Thanks for the exhaustive explanation of how it works!
I guess i should close this thread now due to your answer.
