### ISSUE TITLE
Multi-line text in staticHistory

### ISSUE THREAD

**Issue by b0x4it** [erebe/greenclip#78]
Is it possible to have multi-line text in staticHistory?

**Comment by erebe** [comment]
Hello,

With a bit of trickery yes
```
printf 'a\xA0b\xA0c' > static_history
iconv -f latin1 -t utf-8 static_history > static_history.tmp
iconv -f latin1 -t utf-8 static_history.tmp > static_history
mv static_history ~/.cache/greenclip.staticHistory
```

`\xA0` is a void character used internally by greenclip to replace `\n`. We inject it with printf instead of `\n` and convert the file until it is a valid utf-8 file.
After that the \xA0 will be present as a valid utf-8 and will be replaced by \n by greenclip

Not very user friendly but it works...

**Comment by b0x4it** [comment]
Great, thank you!

**Comment by erebe** [comment]
done in version 4.0
static history is now in the config file
```
static_history = [
 '''¯\_(ツ)_/¯''',
]
```
