### ISSUE TITLE
High CPU and power consumption

### ISSUE THREAD

**Issue by Eucyon** [erebe/greenclip#87]
I like greenclip especially because of its simplicity.

Nevertheless, tools like htop and powertop report a quite high CPU consumption.

Is it possible to optimize its power consumption?

Thank you!

**Comment by erebe** [comment]
Hello,
Yes I know for the high CPU consumption, and this is due to the design of greenclip.
You can see my answer on this issue to understand why https://github.com/erebe/greenclip/issues/71

Basically, it is a tradeoff for simplicity vs performance. Xorg clipboard sucks, and in order for greenclip to be able to works easily without breaking anything/other app, it needs to behave this way. Sadly this behavior/design choice is less than performant.
