### ISSUE TITLE
Noticeable delay until selection shows up in greenclip

### ISSUE THREAD

**Issue by chrissound** [erebe/greenclip#88]
Just thought I'd note this behavior down, please excuse the lack of details - I'll aim to provide more details / debug this some time in the future.

With my current config:
```
Config {
 maxHistoryLength = 500,
 historyPath = "~/.cache/greenclip.history",
 staticHistoryPath = "~/.cache/greenclip.staticHistory",
 imageCachePath = "/tmp/",
 usePrimarySelectionAsInput = True,
 blacklistedApps = [],
 trimSpaceFromSelection = True
}
```

```
greenclip --version
greenclip v3.2 -- Recyle your clipboard selections
```

If I select some text, it takes a few seconds to show up in rofi. However if I copy the text to the other clipboard type (right click > copy) it's instantaneous. This issue seems to crop up only occasionally.

**Comment by erebe** [comment]
Sorry I haven't seen your issue, for unknow reasons.

Selection are store in memory, when there is a huge delay, it is usually due to the time to dump your history through the pipe to rofi.
The bigger your history is, the longer it will take.

If you are used to store a lot of data (especially image) in your clipboard try to:
 1. Disable image handling in the config
 2. Reduce the number of max entries in the history
