### ISSUE TITLE
Config gets rewritten every time the daemon starts

### ISSUE THREAD

**Issue by hashworks** [erebe/greenclip#9]
Procedure:
* Start and stop `greenclip daemon`
* Edit `~/.config/greenclip.cfg`, changing `maxHistoryLength` from `15` to `100`
* Start and stop `greenclip daemon` again
* View `~/.config/greenclip.cfg` and `maxHistoryLength` is back on `15`

Same goes for all other config variables.
I tried setting `chmod 400` on the config, but that results in `openBinaryFile: permission denied (Permission denied)`.

I'm using the Arch Linux AUR package.

**Comment by erebe** [comment]
Indeed, thank you for reporting it.
Rewritting the config file each time is the intended behavior, it let me manage the case where there is no config file, but it should not rewrite it with default values if one already exist. I should have broken it when I improved the utf-8 management.

I will release a new version with the fix for this evening, so stay tuned ! And thanks again to have taken time to report it.

**Comment by erebe** [comment]
It should be good now, I released a new version on github and AUR.
Let me know if it is not fixed.

**Comment by hashworks** [comment]
Works now, thanks! Did you intent to leave [line 121](https://github.com/erebe/greenclip/commit/6ca031d86faa6f76f453ebdbab0a61e4103f4410#diff-f8f3412da88cd4806f23d59fe59ebc3bR121) in?

**Comment by erebe** [comment]
arf fixing that

**Comment by hashworks** [comment]
Works now :) Thanks for your fast response!
